- name: create cluster role binding '{{k8s_resource_clusterrolebinding_params.name}}'
  k8s:
    definition: "{{lookup('template', 'clusterrolebinding.yaml.j2')}}"
    state: present
  delegate_to: localhost
