model_list:
  - model_name: main
    litellm_params:
      api_base: http://vllm-coding-model:8000/v1
      api_key: none
      model: openai/main
    model_info:
      mode: chat

  - model_name: embedding
    litellm_params:
      additional_drop_params:
        - dimensions
      api_base: http://tei-embedding-model:8080/v1
      api_key: none
      model: openai/bge-m3
    model_info:
      mode: embedding

  - model_name: stt
    litellm_params:
      api_base: http://audio-cpp:8080/v1
      api_key: none
      model: openai/stt-default
    model_info:
      mode: audio_transcription

  - model_name: task
    litellm_params:
      allowed_openai_params:
        - reasoning_effort
      api_base: http://llama-task-model:8080/v1
      api_key: none
      model: openai/task
    model_info:
      mode: chat

  - model_name: tts
    litellm_params:
      api_base: http://audio-cpp:8080/v1
      api_key: none
      model: openai/tts-default
    model_info:
      mode: audio_speech
