dependencies:
  - role: k8s/resource/helm
    vars:
      k8s_resource_helm_params:
        chart: stable/nginx-ingress
        chart_values: "{{k8s_component_nginx_params.config}}"
        namespace: "{{k8s_component_nginx_params.namespace}}"
        release: "{{k8s_component_nginx_params.prefix}}"
