- name: install extra Homebrew packages
  homebrew:
    name: "{{item}}"
    state: present
  loop: "{{mac_misc_params.homebrew_packages}}"
  when: mac_misc_params.homebrew_packages is defined

- name: install extra Homebrew cask packages
  homebrew_cask:
    name: "{{item}}"
    state: present
  loop: "{{mac_misc_params.homebrew_cask_packages}}"
  when: mac_misc_params.homebrew_cask_packages is defined
