- block:
  - name: get info for account '{{item.key}}'
    set_fact:
      k8s_app_postgresql_internal_account_info: "{{lookup('hashi_vault', vault_lookup~'accounts/'~item.key)}}"

  - name: create account '{{item.key}}'
    postgresql_user:
      db: "{{database}}"
      encrypted: true
      login_host: "{{k8s_app_postgresql_params.hostname}}"
      login_password: "{{k8s_app_postgresql_params.password}}"
      login_user: "{{k8s_app_postgresql_params.username | default(k8s_app_postgresql_defaults.username)}}"
      name: "{{item.key}}"
      password: "{{k8s_app_postgresql_internal_account_info.password}}"
      port: "{{k8s_app_postgresql_params.port | default(k8s_app_postgresql_defaults.port)}}"
      priv: ALL
      role_attr_flags: NOCREATEDB,NOCREATEROLE,NOSUPERUSER
    loop: "{{item.value.databases}}"
    loop_control:
      loop_var: database
    when: item.value.databases is defined

  - name: remove PUBLIC privileges on all initial databases
    postgresql_privs:
      db: "{{database}}"
      login_host: "{{k8s_app_postgresql_params.hostname}}"
      login_password: "{{k8s_app_postgresql_params.password}}"
      login_user: "{{k8s_app_postgresql_params.username | default(k8s_app_postgresql_defaults.username)}}"
      port: "{{k8s_app_postgresql_params.port | default(k8s_app_postgresql_defaults.port)}}"
      privs: ALL
      roles: PUBLIC
      state: absent
      type: database
    loop: "{{item.value.databases}}"
    loop_control:
      loop_var: database
    when: item.value.databases is defined
  delegate_to: localhost
