dependencies:
  - role: k8s/resource/namespace
    vars:
      k8s_resource_namespace_params:
        labels:
          cert-manager.io/disable-validation: "true"
        name: "{{k8s_component_certmanager_params.namespace | default(k8s_component_certmanager_defaults.namespace)}}"
