- hosts: work
  roles:
    - role: mac/base
      tags:
        - work.base
      vars:
        mac_base_params:
          group: staff
          sudo_password: "{{accounts.work.password}}"
          username: "{{accounts.work.username}}"

    - role: mac/misc
      tags:
        - work.misc
      vars:
        mac_misc_params:
          homebrew_packages:
            - node
            - terraform
          homebrew_cask_packages:
            - intellij-idea
            - microsoft-excel
            - microsoft-outlook
            - microsoft-powerpoint
            - onedrive
            - slack
            - wkhtmltopdf
            - zoomus
          sudo_password: "{{accounts.work.password}}"

    - role: mac/dock
      tags:
        - work.dock
      vars:
        mac_dock_params:
          dock_items:
            - /System/Applications/Launchpad.app
            - "\"/System/Applications/System Preferences.app\""
            - /Applications/Bitwarden.app
            - "\"/System/Applications/Utilities/Activity Monitor.app\""
            - /Applications/iTerm.app
            - "\"/Applications/IntelliJ IDEA.app\""
            - /Applications/Safari.app
            - "\"/Applications/Google Chrome.app\""
            - /System/Applications/Mail.app
            - "\"/Applications/Microsoft Outlook.app\""
            - /System/Applications/Calendar.app
            - /System/Applications/Messages.app
            - /Applications/Slack.app
            - /Applications/zoom.us.app
            - "\"/System/Applications/App Store.app\""
            - ~/Downloads --section others

    - role: mac/dotfiles
      tags:
        - work.dotfiles
      vars:
        mac_dotfiles_params:
          repo: https://github.com/handcraftedbits/dotfiles.git
          username: "{{accounts.work.username}}"

    - role: mac/sdkman
      tags:
        - work.sdkman
      mac_sdkman_params:
        username: "{{accounts.work.username}}"

    - role: mac/tmux
      tags:
        - work.tmux
      mac_tmux_params:
        username: "{{accounts.work.username}}"

    - role: mac/vim
      tags:
        - work.vim
      mac_vim_params:
        username: "{{accounts.work.username}}"

    - role: mac/zsh
      tags:
        - work.zsh
      mac_zsh_params:
        username: "{{accounts.work.username}}"
