- name: create statefulset spec
  set_fact:
    k8s_app_pgadmin_internal_spec: "{{lookup('template', 'spec.yaml.j2') | from_yaml}}"

- include_role:
    name: k8s/resource/statefulset
  vars:
    k8s_resource_statefulset_params:
      labels:
        app: "{{k8s_app_pgadmin_internal.app_name}}"
      name: "{{k8s_app_pgadmin_params.name}}"
      namespace: "{{k8s_app_pgadmin_params.namespace | default(k8s_app_pgadmin_defaults.namespace)}}"
      spec: "{{k8s_app_pgadmin_internal_spec}}"
