- name: create persistent volume claim '{{k8s_resource_persistentvolumeclaim_params.name}}'
  k8s:
    definition: "{{lookup('template', 'persistentvolumeclaim.yaml.j2')}}"
    state: present
  delegate_to: localhost
